version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - apt update
      - apt install -y python3-dev gcc
      - pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
      - pip install fastai
      - pip install starlette uvicorn python-multipart aiohttp
    finally:
      - echo This always runs just before build. do login here 
  build:
    commands:
      - python application.py
    finally:
      - pwd
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - 'application.py'
    - 'export.pkl'
  base-directory: ''
